# Generated by Django 2.2.18 on 2021-06-14 22:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allauthdemo_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automotive',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField(default=0)),
                ('make', models.CharField(default='Toyota', max_length=25)),
                ('model', models.CharField(default='Corolla', max_length=100)),
                ('year', models.IntegerField(default=2010)),
                ('experience', models.IntegerField(default=0)),
                ('third_party', models.FloatField(default=200000)),
                ('statutory_accident', models.FloatField(default=65000)),
                ('uninsured_auto', models.FloatField(default=200000)),
                ('income_replacement', models.FloatField(blank=True, null=True)),
                ('medical', models.FloatField(blank=True, null=True)),
                ('caregiver', models.FloatField(blank=True, null=True)),
                ('housekeeping', models.FloatField(blank=True, null=True)),
                ('death', models.FloatField(blank=True, null=True)),
                ('dependent', models.FloatField(blank=True, null=True)),
                ('indexation', models.FloatField(blank=True, null=True)),
                ('specified_perils', models.FloatField(blank=True, null=True)),
                ('comprehensive', models.FloatField(blank=True, null=True)),
                ('collision', models.FloatField(blank=True, null=True)),
                ('all_perils', models.FloatField(blank=True, null=True)),
                ('start', models.DateField(default=datetime.date.today)),
                ('end', models.DateField(default=datetime.date.today)),
                ('monthly_premium', models.FloatField(default=150)),
            ],
            options={
                'verbose_name': 'automotive',
            },
        ),
        migrations.CreateModel(
            name='Disability',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField(default=0)),
                ('coverage', models.FloatField(default=35000)),
                ('benefit_period', models.IntegerField(default=1)),
                ('waiting_period', models.IntegerField(default=0)),
                ('age', models.IntegerField(default=40)),
                ('health', models.IntegerField(default=10)),
                ('occupation', models.CharField(default='B', max_length=1)),
                ('start', models.DateField(default=datetime.date.today)),
                ('end', models.DateField(default=datetime.date.today)),
                ('monthly_premium', models.FloatField(default=100)),
            ],
            options={
                'verbose_name': 'disability',
            },
        ),
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField(default=0)),
                ('age', models.IntegerField(default=40)),
                ('sex', models.CharField(default='M', max_length=2)),
                ('bmi', models.FloatField(default=20.0)),
                ('children', models.IntegerField(default=2)),
                ('smoker', models.BooleanField(default=False)),
                ('region', models.TextField(default='southeast', max_length=10)),
                ('start', models.DateField(default=datetime.date.today)),
                ('end', models.DateField(default=datetime.date.today)),
                ('monthly_premium', models.FloatField(default=150)),
            ],
            options={
                'verbose_name': 'health',
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField(default=0)),
                ('dwelling', models.FloatField(default=10000)),
                ('contents', models.FloatField(default=10000)),
                ('personal_liability', models.FloatField(default=10000)),
                ('flood', models.FloatField(blank=True, null=True)),
                ('windstorm', models.FloatField(blank=True, null=True)),
                ('sewer_backup', models.FloatField(blank=True, null=True)),
                ('scheduled_articles', models.FloatField(blank=True, null=True)),
                ('equipment_breakdown', models.FloatField(blank=True, null=True)),
                ('guaranteed_replacement', models.FloatField(blank=True, null=True)),
                ('earthquake', models.FloatField(blank=True, null=True)),
                ('start', models.DateField(default=datetime.date.today)),
                ('end', models.DateField(default=datetime.date.today)),
                ('monthly_premium', models.FloatField(default=100)),
            ],
            options={
                'verbose_name': 'house',
            },
        ),
        migrations.CreateModel(
            name='Life',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField(default=0)),
                ('whole', models.BooleanField(default=False)),
                ('universal', models.BooleanField(default=False)),
                ('annual_renewable', models.BooleanField(default=False)),
                ('fixed_traditional', models.BooleanField(default=False)),
                ('fixed_reentry', models.BooleanField(default=False)),
                ('decreasing_level', models.BooleanField(default=False)),
                ('decreasing_mortgage', models.BooleanField(default=False)),
                ('start', models.DateField(default=datetime.date.today)),
                ('end', models.DateField(default=datetime.date.today)),
                ('next_premium', models.FloatField(default=1000)),
            ],
            options={
                'verbose_name': 'life',
            },
        ),
    ]
