# Generated by Django 2.2.18 on 2021-06-28 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allauthdemo_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automotive',
            name='company',
            field=models.CharField(default='The Co-operators', max_length=25),
        ),
    ]
