# Generated by Django 2.2.18 on 2021-07-13 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allauthdemo_auth', '0002_automotive_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthrates',
            old_name='premium',
            new_name='profit',
        ),
        migrations.RemoveField(
            model_name='healthrates',
            name='coverage',
        ),
        migrations.AddField(
            model_name='health',
            name='company',
            field=models.CharField(default='Anthem', max_length=25),
        ),
        migrations.AlterField(
            model_name='automotive',
            name='all_perils',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='automotive',
            name='caregiver',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='automotive',
            name='collision',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='automotive',
            name='comprehensive',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='automotive',
            name='death',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='automotive',
            name='dependent',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='automotive',
            name='housekeeping',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='automotive',
            name='income_replacement',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='automotive',
            name='indexation',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='automotive',
            name='medical',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='automotive',
            name='specified_perils',
            field=models.FloatField(default=0),
        ),
    ]
