# Generated by Django 2.2.18 on 2021-06-19 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allauthdemo_auth', '0002_automotive_disability_health_house_life'),
    ]

    operations = [
        migrations.AddField(
            model_name='life',
            name='coverage',
            field=models.FloatField(default=10000),
        ),
    ]
