# Generated by Django 2.2.18 on 2021-08-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allauthdemo_auth', '0005_auto_20210726_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automotive',
            name='monthly_premium',
            field=models.FloatField(default=230),
        ),
        migrations.AlterField(
            model_name='disability',
            name='monthly_premium',
            field=models.FloatField(default=120),
        ),
        migrations.AlterField(
            model_name='health',
            name='monthly_premium',
            field=models.FloatField(default=236),
        ),
        migrations.AlterField(
            model_name='house',
            name='earthquake',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='house',
            name='equipment_breakdown',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='house',
            name='flood',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='house',
            name='guaranteed_replacement',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='house',
            name='scheduled_articles',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='house',
            name='sewer_backup',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='house',
            name='windstorm',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='life',
            name='next_premium',
            field=models.FloatField(default=125),
        ),
    ]
